### ISSUE TITLE
Front-end - Multi entorno con sass, bootstrap y jquery

### ISSUE THREAD

**Issue by CarlosRayon** [CarlosRayon/symfony#42]
# Un entorno

Antes de nada tirar de la documentacion. Este issue que sirva de apoyo:

<https://symfony.com/doc/current/frontend/encore/installation.html>
<https://symfony.com/doc/4.4/frontend/encore/bootstrap.html>

Instalamos encore bundle, boostrap, jquery las depedencias necesarias:

```bash
composer require symfony/webpack-encore-bundle
yarn add bootstrap --dev # instala la ^5 si queremos al 4 yarn add bootstrap@4.6 --dev
yarn add jquery popper.js --dev
yarn add sass-loader@^11.0.0 sass --dev
yarn add @fortawesome/fontawesome-free --dev
yarn add sweetalert2 --dev
yarn add datatables.net-bs4
yarn install
```

Vamos a webpack.config.js y descomentamos:

```js
  // enables Sass/SCSS support
    .enableSassLoader()

    // uncomment if you're having problems with a jQuery plugin
    .autoProvidejQuery();

```

Vamos a assets/styles/app.scss y añadimos

```scss
@import "~bootstrap/scss/bootstrap";
@import "~@fortawesome/fontawesome-free/css/all.min.css";
```

Vamos a assets/app.js e incluimos las dependencias:

```js

// any CSS you import will output into a single css file (app.css in this case)
import '../styles/app.scss';

// start the Stimulus application
import '../bootstrap';

/* jquery */
const $ = require('jquery');

/* Popper */
require('popper.js');

/* Boostrap */
require('bootstrap');

/* Fontawesome */
import '@fortawesome/fontawesome-free/js/all.min.js';

/* SweetAlert2*/
const Swal = require('sweetalert2');
window.Swal = Swal;

/* DataTable */
require('datatables.net-bs4');
import './handlerDataTable.js';

```

---

# Multi entorno

Dentro de _assets_ creamos dos directorios para cada entorno y dentro de cada entorno un fichero **webpack.config.js** de configuración. Tendremos algo así:

![directorios](https://user-images.githubusercontent.com/40696767/116091355-06dea000-a6a5-11eb-9450-6f0121deeb73.png)

Configuramos el **webpack.config.js** de cada entorno (ejemplo para entorno back, para front cambiar rutas):

```js
const Encore = require('@symfony/webpack-encore');
if (!Encore.isRuntimeEnvironmentConfigured()) {
    Encore.configureRuntimeEnvironment(process.env.NODE_ENV || 'dev');
}

Encore
    .setOutputPath('public/assets/back/')
    .setPublicPath('/assets/back')
    .addEntry('back', './assets/back/js/app.js')
    .enableStimulusBridge('./assets/controllers.json')
    .splitEntryChunks()
    .enableSingleRuntimeChunk()
    .cleanupOutputBeforeBuild()
    .enableBuildNotifications()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())
    .configureBabel((config) => {
        config.plugins.push('@babel/plugin-proposal-class-properties');
    })
    .configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;
    })
    .enableSassLoader()
    .autoProvidejQuery();

const config = Encore.getWebpackConfig();
config.name = 'back';
module.exports = config;
```

Configuramos el **webpack.config.js** del directorio raiz del proyecto para cargar cada entorno por separado:

```js
const Encore = require('@symfony/webpack-encore');
const front = require('./assets/front/webpack.config');
Encore.reset();
const back = require('./assets/back/webpack.config');
module.exports = [front,back];
```

Tenemos que configurar tambien el fichero de configuracion **webpack_encore.yaml**

```yaml
webpack_encore:
    output_path: false
    builds:
        front: "%kernel.project_dir%/public/assets/front"
        back: "%kernel.project_dir%/public/assets/back"

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
```

Y el fichero **assets.yaml**

```yaml
framework:
   assets:
        packages:
            front:
                json_manifest_path: '%kernel.project_dir%/public/assets/front/manifest.json'
            office:
                json_manifest_path: '%kernel.project_dir%/public/assets/office/manifest.json'
```

Los fichero **app.js y app.scss** de cada entorno quedaran asi:

```scss
@import "~bootstrap/scss/bootstrap";
@import "~@fortawesome/fontawesome-free/css/all.min.css";
```

```js
import '../sass/app.scss';
const $ = require('jquery');
// start the Stimulus application
import '../../bootstrap';
```

Compilamos y en el directorio _public_ debemos tener:

![compilamos](https://user-images.githubusercontent.com/40696767/116092831-6db08900-a6a6-11eb-8ac8-5baf036b33ae.png)

Desde twig cargamos cada fichero de la siguiente manera:

```php
     {% block stylesheets %}
            {{ encore_entry_link_tags('back', null, 'back') }}
        {% endblock %}

     {% block javascripts %}
            {{ encore_entry_script_tags('back', null, 'back') }}
        {% endblock %}
```
