### ISSUE TITLE
Test Funcional: Simular autentifican

### ISSUE THREAD

**Issue by CarlosRayon** [CarlosRayon/symfony#9]
Para simular la autenticacion por formulario, creamos un `config/packages/test/security.yaml` con la siguiente configuración:

```yaml
# config/packages/test/security.yaml
security:
    firewalls:
        # replace 'main' by the name of your own firewall
        main:
            http_basic: ~
```
Luego tenemos dos opciones para establecer login del usuario:

- Creando cliente con los datos acceos
```php
$client = static::createClient([], [
    'PHP_AUTH_USER' => 'username',
    'PHP_AUTH_PW'   => 'pa$$word',
]);
```

- Pasando los datos en la peticion:

```php
$client->request('GET', '/post/12', [], [], [
    'PHP_AUTH_USER' => 'username',
    'PHP_AUTH_PW'   => 'pa$$word',
]);
```
